"""
build_shots.py — validates 40 shot Q→SQL pairs and writes cumulative shot files.

Stratification per block of 10:
  Block 1 (1-10):  3 single-table, 3 two-join, 2 three-join, 2 complex
  Block 2 (11-20): 3 single-table, 3 two-join, 2 three-join, 2 complex
  Block 3 (21-30): 2 single-table, 2 two-join, 3 three-join, 3 complex
  Block 4 (31-40): 2 single-table, 2 two-join, 3 three-join, 3 complex
  Total:          10 per tier across 40 shots.

Schema (opaque names):
  customers : cust_id, name, email, region, plan, joined, rep
  products  : sku, product, cat, price  (cents)
  orders    : oid, cust_id, sku, dt, qty, unit_price, discount, revenue, refunded
"""
import json, sqlite3, sys
from pathlib import Path

BASE    = Path(__file__).parent.parent.parent
DB_PATH = BASE / "db" / "orders.db"
OUT_DIR = Path(__file__).parent

SHOTS = [
    # ------------------------------------------------------------------ Block 1
    # single-table
    ("What are the distinct regions in the customers table?",
     "SELECT DISTINCT region FROM customers ORDER BY region"),

    ("What is the highest unit price charged in a single order in dollars?",
     "SELECT ROUND(MAX(unit_price) / 100.0, 2) AS max_unit_price_dollars FROM orders"),

    ("How many products are there in total?",
     "SELECT COUNT(*) AS total_products FROM products"),

    # two-join
    ("What is the total revenue generated by each sales rep in dollars?",
     """SELECT c.rep, ROUND(SUM(o.revenue) / 100.0, 2) AS revenue_dollars
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        WHERE c.rep IS NOT NULL GROUP BY c.rep ORDER BY revenue_dollars DESC"""),

    ("Which product SKU has the most total units sold?",
     """SELECT p.sku, p.product, SUM(o.qty) AS total_units
        FROM orders o JOIN products p ON o.sku = p.sku
        GROUP BY p.sku ORDER BY total_units DESC LIMIT 1"""),

    ("How many orders did North region customers place in 2023?",
     """SELECT COUNT(*) AS order_count
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        WHERE c.region = 'North' AND o.dt >= '2023-01-01' AND o.dt < '2024-01-01'"""),

    # three-join
    ("What is the total revenue from free plan customers on Support products in dollars?",
     """SELECT ROUND(SUM(o.revenue) / 100.0, 2) AS revenue_dollars
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.plan = 'free' AND p.cat = 'Support'"""),

    ("How many orders did each sales rep close for Hardware products?",
     """SELECT c.rep, COUNT(*) AS order_count
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.rep IS NOT NULL AND p.cat = 'Hardware'
        GROUP BY c.rep ORDER BY order_count DESC"""),

    # complex
    ("For each product category, what is the average revenue per distinct customer in dollars?",
     """SELECT p.cat,
               ROUND(SUM(o.revenue) / 100.0 / COUNT(DISTINCT o.cust_id), 2) AS avg_rev_per_customer_dollars
        FROM orders o JOIN products p ON o.sku = p.sku
        GROUP BY p.cat ORDER BY avg_rev_per_customer_dollars DESC"""),

    ("Which customers have ordered more distinct products than the average customer?",
     """SELECT c.name, c.plan, COUNT(DISTINCT o.sku) AS distinct_products
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        GROUP BY c.cust_id
        HAVING COUNT(DISTINCT o.sku) > (
            SELECT AVG(cnt) FROM (SELECT COUNT(DISTINCT sku) AS cnt FROM orders GROUP BY cust_id)
        )
        ORDER BY distinct_products DESC"""),

    # ------------------------------------------------------------------ Block 2
    # single-table
    ("What are the earliest and latest order dates in the dataset?",
     "SELECT MIN(dt) AS earliest_order, MAX(dt) AS latest_order FROM orders"),

    ("How many customers signed up before 2023?",
     "SELECT COUNT(*) AS pre_2023_customers FROM customers WHERE joined < '2023-01-01'"),

    ("What is the most expensive product in each category in dollars?",
     """SELECT cat, ROUND(MAX(price) / 100.0, 2) AS max_price_dollars
        FROM products GROUP BY cat ORDER BY max_price_dollars DESC"""),

    # two-join
    ("What is the total number of units sold per customer plan type?",
     """SELECT c.plan, SUM(o.qty) AS total_units
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        GROUP BY c.plan ORDER BY total_units DESC"""),

    ("What is the revenue from refunded orders by product category in dollars?",
     """SELECT p.cat, ROUND(SUM(o.revenue) / 100.0, 2) AS refunded_revenue_dollars
        FROM orders o JOIN products p ON o.sku = p.sku
        WHERE o.refunded = 1 GROUP BY p.cat ORDER BY refunded_revenue_dollars DESC"""),

    ("What is the average quantity per order for each customer plan type?",
     """SELECT c.plan, ROUND(AVG(o.qty), 2) AS avg_qty
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        GROUP BY c.plan ORDER BY avg_qty DESC"""),

    # three-join
    ("What is the total revenue from East region customers buying Services products in dollars?",
     """SELECT ROUND(SUM(o.revenue) / 100.0, 2) AS revenue_dollars
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.region = 'East' AND p.cat = 'Services'"""),

    ("How many distinct products has each sales rep sold?",
     """SELECT c.rep, COUNT(DISTINCT o.sku) AS distinct_products
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.rep IS NOT NULL GROUP BY c.rep ORDER BY distinct_products DESC"""),

    # complex
    ("For each region, what percentage of orders were placed by enterprise customers?",
     """SELECT c.region,
               ROUND(100.0 * SUM(CASE WHEN c.plan = 'enterprise' THEN 1 ELSE 0 END) / COUNT(*), 2) AS enterprise_order_pct
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        GROUP BY c.region ORDER BY enterprise_order_pct DESC"""),

    ("Which products have been ordered by customers from every plan type?",
     """SELECT p.product
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        GROUP BY p.sku
        HAVING COUNT(DISTINCT c.plan) = (SELECT COUNT(DISTINCT plan) FROM customers)
        ORDER BY p.product"""),

    # ------------------------------------------------------------------ Block 3
    # single-table
    ("What is the total revenue from orders placed on weekends in dollars?",
     """SELECT ROUND(SUM(revenue) / 100.0, 2) AS weekend_revenue_dollars
        FROM orders WHERE strftime('%w', dt) IN ('0', '6')"""),

    ("How many orders were placed in the first half of 2024?",
     "SELECT COUNT(*) AS h1_2024_orders FROM orders WHERE dt >= '2024-01-01' AND dt < '2024-07-01'"),

    # two-join
    ("Which sales rep has the most distinct customers?",
     """SELECT c.rep, COUNT(DISTINCT c.cust_id) AS customer_count
        FROM customers c JOIN orders o ON c.cust_id = o.cust_id
        WHERE c.rep IS NOT NULL GROUP BY c.rep ORDER BY customer_count DESC LIMIT 1"""),

    ("What is the refund rate for orders from customers who signed up in 2022?",
     """SELECT ROUND(100.0 * SUM(o.refunded) / COUNT(*), 2) AS refund_rate_pct
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        WHERE c.joined >= '2022-01-01' AND c.joined < '2023-01-01'"""),

    # three-join
    ("What is the average unit price paid by each plan type for each product category in dollars?",
     """SELECT c.plan, p.cat, ROUND(AVG(o.unit_price) / 100.0, 2) AS avg_unit_price_dollars
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        GROUP BY c.plan, p.cat ORDER BY c.plan, avg_unit_price_dollars DESC"""),

    ("How many refunded orders were there by region and product category?",
     """SELECT c.region, p.cat, COUNT(*) AS refunded_count
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE o.refunded = 1
        GROUP BY c.region, p.cat ORDER BY c.region, refunded_count DESC"""),

    ("What is the total quantity of Hardware products sold by customer region?",
     """SELECT c.region, SUM(o.qty) AS total_units
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE p.cat = 'Hardware' GROUP BY c.region ORDER BY total_units DESC"""),

    # complex
    ("For each sales rep, what is their best-selling product by revenue?",
     """SELECT rep, product, revenue_dollars FROM (
            SELECT c.rep, p.product,
                   ROUND(SUM(o.revenue) / 100.0, 2) AS revenue_dollars,
                   RANK() OVER (PARTITION BY c.rep ORDER BY SUM(o.revenue) DESC) AS rnk
            FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                          JOIN products p ON o.sku = p.sku
            WHERE c.rep IS NOT NULL GROUP BY c.rep, p.sku
        ) WHERE rnk = 1 ORDER BY rep"""),

    ("What is the revenue by product category in 2023 versus 2024 in dollars?",
     """SELECT p.cat,
               ROUND(SUM(CASE WHEN o.dt >= '2023-01-01' AND o.dt < '2024-01-01' THEN o.revenue ELSE 0 END) / 100.0, 2) AS rev_2023_dollars,
               ROUND(SUM(CASE WHEN o.dt >= '2024-01-01' AND o.dt < '2025-01-01' THEN o.revenue ELSE 0 END) / 100.0, 2) AS rev_2024_dollars
        FROM orders o JOIN products p ON o.sku = p.sku
        GROUP BY p.cat ORDER BY p.cat"""),

    ("What is the cumulative number of customers who had signed up by the end of each month in 2023?",
     """SELECT strftime('%Y-%m', joined) AS month,
               SUM(COUNT(*)) OVER (ORDER BY strftime('%Y-%m', joined)) AS cumulative_customers
        FROM customers WHERE joined >= '2023-01-01' AND joined < '2024-01-01'
        GROUP BY month ORDER BY month"""),

    # ------------------------------------------------------------------ Block 4
    # single-table
    ("What is the total revenue from non-refunded orders in dollars?",
     "SELECT ROUND(SUM(revenue) / 100.0, 2) AS non_refunded_revenue_dollars FROM orders WHERE refunded = 0"),

    ("How many customers are on each combination of plan and region?",
     """SELECT plan, region, COUNT(*) AS customer_count
        FROM customers GROUP BY plan, region ORDER BY plan, customer_count DESC"""),

    # two-join
    ("What is the average order value for customers with a sales rep versus those without one in dollars?",
     """SELECT CASE WHEN c.rep IS NULL THEN 'No rep' ELSE 'Has rep' END AS rep_status,
               ROUND(AVG(o.revenue) / 100.0, 2) AS avg_order_value_dollars
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
        GROUP BY rep_status ORDER BY rep_status"""),

    ("Which products have been ordered by more than 20 distinct customers?",
     """SELECT p.product, COUNT(DISTINCT o.cust_id) AS customer_count
        FROM orders o JOIN products p ON o.sku = p.sku
        GROUP BY p.sku HAVING COUNT(DISTINCT o.cust_id) > 20
        ORDER BY customer_count DESC"""),

    # three-join
    ("How many orders were placed by starter plan customers for each product category?",
     """SELECT p.cat, COUNT(*) AS order_count
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.plan = 'starter' GROUP BY p.cat ORDER BY order_count DESC"""),

    ("What is the average order revenue for West region customers buying Software products in dollars?",
     """SELECT ROUND(AVG(o.revenue) / 100.0, 2) AS avg_order_revenue_dollars
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.region = 'West' AND p.cat = 'Software'"""),

    ("For each sales rep, how many distinct enterprise customers have ordered Hardware products?",
     """SELECT c.rep, COUNT(DISTINCT c.cust_id) AS enterprise_hardware_customers
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        WHERE c.plan = 'enterprise' AND p.cat = 'Hardware' AND c.rep IS NOT NULL
        GROUP BY c.rep ORDER BY enterprise_hardware_customers DESC"""),

    # complex
    ("For each region, what is the revenue share percentage of each product category?",
     """SELECT c.region, p.cat,
               ROUND(100.0 * SUM(o.revenue) / SUM(SUM(o.revenue)) OVER (PARTITION BY c.region), 2) AS revenue_share_pct
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        GROUP BY c.region, p.cat ORDER BY c.region, revenue_share_pct DESC"""),

    ("What is the revenue rank of each product within its category?",
     """SELECT p.cat, p.product,
               ROUND(SUM(o.revenue) / 100.0, 2) AS revenue_dollars,
               RANK() OVER (PARTITION BY p.cat ORDER BY SUM(o.revenue) DESC) AS revenue_rank
        FROM orders o JOIN products p ON o.sku = p.sku
        GROUP BY p.sku ORDER BY p.cat, revenue_rank"""),

    ("For each plan type, what is the average order revenue in dollars ranked from highest to lowest?",
     """SELECT c.plan,
               ROUND(AVG(o.revenue) / 100.0, 2) AS avg_order_revenue_dollars,
               RANK() OVER (ORDER BY AVG(o.revenue) DESC) AS revenue_rank
        FROM orders o JOIN customers c ON o.cust_id = c.cust_id
                      JOIN products p ON o.sku = p.sku
        GROUP BY c.plan ORDER BY revenue_rank"""),
]


def build():
    con = sqlite3.connect(DB_PATH)
    errors = []

    for i, (question, sql) in enumerate(SHOTS, 1):
        try:
            con.execute(sql).fetchall()
        except Exception as e:
            errors.append((i, str(e), question[:60]))

    con.close()

    if errors:
        print(f"{len(errors)} SQL errors:")
        for i, err, q in errors:
            print(f"  shot {i}: {err} — {q}")
        sys.exit(1)

    records = [{"question": q, "sql": s.strip()} for q, s in SHOTS]

    for n in [10, 20, 30, 40]:
        path = OUT_DIR / f"shots_{n:02d}.json"
        with open(path, "w") as f:
            json.dump(records[:n], f, indent=2)
        print(f"Wrote {path.name} ({n} shots)")

    print(f"\nAll {len(SHOTS)} shots validated and written.")


if __name__ == "__main__":
    build()
